-- Database creation (optional, remove if already created manually)
-- CREATE DATABASE IF NOT EXISTS tiles_site DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
-- USE tiles_site;

-- TileTypes Table
CREATE TABLE TileTypes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL UNIQUE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- TileSizes Table
CREATE TABLE TileSizes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  size VARCHAR(20) NOT NULL UNIQUE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Tiles Table
CREATE TABLE Tiles (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  slug VARCHAR(100) NOT NULL UNIQUE,
  type_id INT NOT NULL,
  size_id INT NOT NULL,
  description TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (type_id) REFERENCES TileTypes(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (size_id) REFERENCES TileSizes(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- TileImages Table
CREATE TABLE TileImages (
  id INT AUTO_INCREMENT PRIMARY KEY,
  tile_id INT NOT NULL,
  image_url VARCHAR(255) NOT NULL,
  is_primary BOOLEAN DEFAULT FALSE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (tile_id) REFERENCES Tiles(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Reviews Table (general reviews, not tied to a specific tile)
CREATE TABLE Reviews (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  role VARCHAR(100),
  review TEXT NOT NULL,
  star INT NOT NULL CHECK (star BETWEEN 1 AND 5),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
